(( workflow_header ))
name: CD

on:
  push:
    tags:
      - '**'
      - '!v*'

jobs:
  check-release-tag:
    name: Check Release Tag
    uses: ./.github/workflows/check-release-tag.yml
    permissions:
      contents: read

  build-and-publish:
    needs:
      - check-release-tag
    name: Build & Publish
    uses: ./.github/workflows/build-and-publish.yml
    permissions:
      contents: write
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  (% if workflow_extension.cd %)
  cd-extension:
    name: CD Extension
    uses: ./.github/workflows/cd-extension.yml
    needs:
      - check-release-tag
    secrets: inherit # zizmor: ignore[secrets-inherit] - PTB cannot customize inherited secrets here yet; tracked in https://github.com/exasol/python-toolbox/issues/872.
    permissions:
      contents: write
  (% endif %)

  publish-docs:
    needs:
      - build-and-publish
    name: Publish Documentation
    uses: ./.github/workflows/gh-pages.yml
    permissions:
      contents: read
      pages: write
      id-token: write
