name: Check Release Tag

on:
  workflow_call:

jobs:

  check-release-tag:
    name: Check Release Tag
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    steps:
      - name: Check out Repository
        id: check-out-repository
        uses: actions/checkout@v6

      - name: Set up Python & Poetry Environment
        id: set-up-python-and-poetry-environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: "(( minimum_python_version ))"
          poetry-version: "(( dependency_manager_version ))"

      - name: Check Release Tag
        id: check-release-tag
        # make sure the pushed/created tag matched the project version
        run: "[[ `poetry version --short` == ${{ github.ref_name }} ]]"
