name: Checks

on:
  workflow_call:

jobs:
  Version-Check:
    name: Version
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: "(( minimum_python_version ))"
          poetry-version: "(( dependency_manager_version ))"

      - name: Check Version(s)
        run: poetry run -- nox -s version:check

  Documentation:
    name: Docs
    needs: [ Version-Check ]
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: "(( minimum_python_version ))"
          poetry-version: "(( dependency_manager_version ))"

      - name: Build Documentation
        run: |
          poetry run -- nox -s docs:build

      - name: Link Check
        run: |
          poetry run -- nox -s links:check

  Changelog:
    name: Changelog Update Check
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: "(( minimum_python_version ))"
          poetry-version: "(( dependency_manager_version ))"

      - name: Run changelog update check
        run: poetry run -- nox -s changelog:updated

  Lint:
    name: Linting (Python-${{ matrix.python-versions }})
    needs: [ Version-Check ]
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-versions: (( python_versions | tojson ))
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: ${{ matrix.python-versions }}
          poetry-version: "(( dependency_manager_version ))"

      - name: Run lint
        run: poetry run -- nox -s lint:code

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: lint-python${{ matrix.python-versions }}
          path: |
            .lint.txt
            .lint.json
          include-hidden-files: true

  Type-Check:
    name: Type Checking (Python-${{ matrix.python-versions }})
    needs: [ Version-Check ]
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-versions: (( python_versions | tojson ))

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: ${{ matrix.python-versions }}
          poetry-version: "(( dependency_manager_version ))"

      - name: Run type-check
        run: poetry run -- nox -s lint:typing

  Security:
    name: Security Checks (Python-${{ matrix.python-versions }})
    needs: [ Version-Check ]
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-versions: (( python_versions | tojson ))

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: ${{ matrix.python-versions }}
          poetry-version: "(( dependency_manager_version ))"

      - name: Run security linter
        run: poetry run -- nox -s lint:security

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: security-python${{ matrix.python-versions }}
          path: .security.json
          include-hidden-files: true

  Format:
    name: Format Check
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: "(( minimum_python_version ))"
          poetry-version: "(( dependency_manager_version ))"

      - name: Run format check
        run: poetry run -- nox -s format:check


  Build-Packages:
    name: Build Package Check
    needs: [ Documentation, Lint, Type-Check, Security, Format ]
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: "(( minimum_python_version ))"
          poetry-version: "(( dependency_manager_version ))"

      - name: Run Distribution Check
        run: poetry run -- nox -s package:check

  Tests:
    name: Unit-Tests (Python-${{ matrix.python-versions }})
    needs: [ Build-Packages ]
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-versions: (( python_versions | tojson ))

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: ${{ matrix.python-versions }}
          poetry-version: "(( dependency_manager_version ))"

      - name: Run Tests and Collect Coverage
        run: poetry run -- nox -s test:unit -- --coverage

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: coverage-python${{ matrix.python-versions }}-fast
          path: .coverage
          include-hidden-files: true
