name: Check Release Tag

on:
  workflow_call:

jobs:

  check-tag-version-job:
    name: Check Tag Version
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v5
        with:
          python-version: "(( minimum_python_version ))"
          poetry-version: "(( dependency_manager_version ))"

      - name: Check Tag Version
        # make sure the pushed/created tag matched the project version
        run: "[[ `poetry version --short` == ${{ github.ref_name }} ]]"
