name: CI/CD

on:
  push:
    tags:
      - '**'

jobs:

  check-tag-version-job:
    name: Check Release Tag
    uses: exasol/python-toolbox/.github/workflows/check-release-tag.yml@0.5.0

  ci-job:
    name: Checks
    needs: [ check-tag-version-job ]
    uses: exasol/python-toolbox/.github/workflows/checks.yml@0.5.0

  cd-job:
    name: Continues Delivery
    needs: [ ci-job ]
    uses: exasol/python-toolbox/.github/workflows/build-and-publish.yml@0.5.0
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  metrics:
    needs: [ ci-job ]
    uses: exasol/python-toolbox/.github/workflows/report.yml@0.5.0
