(( workflow_header ))
(% from "_workflow_macros.j2" import workflow_permissions with context %)
name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  merge-gate:
    name: Merge Gate
    uses: ./.github/workflows/merge-gate.yml
    (% if custom_workflows["merge-gate"].secrets %)
    secrets:
      (% for secret_name in custom_workflows["merge-gate"].secrets %)
      (( secret_name )): ${{ secrets.(( secret_name )) }}
      (% endfor %)
    (% endif %)
    (( workflow_permissions("merge-gate") | trim ))

  report:
    name: Report
    needs:
      - merge-gate
    # This condition ensures the job runs if merge-gate finished (success or failure)
    if: |
      always() &&
      needs.merge-gate.result != 'skipped' &&
      needs.merge-gate.result != 'cancelled'
    uses: ./.github/workflows/report.yml
    secrets:
      (( sonar_token_name )): ${{ secrets.(( sonar_token_name )) }}
    permissions:
      contents: read
