name: Fast-Tests

on:
  workflow_call:

jobs:
  run-unit-tests:
    name: Unit Tests (Python-${{ matrix.python-versions }})
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-versions: (( python_versions | tojson ))

    steps:
      - name: Check out Repository
        id: check-out-repository
        uses: actions/checkout@v6

      - name: Set up Python & Poetry Environment
        id: set-up-python-and-poetry-environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v7
        with:
          python-version: ${{ matrix.python-versions }}
          poetry-version: "(( dependency_manager_version ))"

      - name: Run Unit Tests
        id: run-unit-tests
        run: poetry run -- nox -s test:unit -- --coverage

      - name: Upload Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v7
        with:
          name: coverage-python${{ matrix.python-versions }}-fast
          path: .coverage
          include-hidden-files: true

(% if workflow_extension.fast_tests %)
  fast-tests-extension:
    uses: ./.github/workflows/fast-tests-extension.yml
    permissions:
      contents: read
  (% endif %)
