(( workflow_header ))
name: Merge-Gate

on:
  workflow_call:
    (% if custom_workflows["merge-gate"].secrets %)
    secrets:
      (% for secret_name in custom_workflows["merge-gate"].secrets %)
        (( secret_name )):
          required: true
      (% endfor %)
    (% endif %)

jobs:
  run-fast-checks:
    name: Fast Checks
    uses: ./.github/workflows/checks.yml
    permissions:
      contents: read

  run-fast-tests:
    name: Fast Tests
    uses: ./.github/workflows/fast-tests.yml
    permissions:
      contents: read

  fast-report:
    name: Fast Report
    needs:
      - run-fast-checks
      - run-fast-tests
    uses: ./.github/workflows/report.yml
    secrets:
      (( sonar_token_name )): ${{ secrets.(( sonar_token_name )) }}
    permissions:
      contents: read

  approve-run-slow-tests:
    name: Approve Running Slow Tests?
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    # Even though the environment "manual-approval" will be created automatically,
    # it still needs to be configured to require interactive review.
    # See project settings on GitHub (Settings / Environments / manual-approval).
    environment: manual-approval
    steps:
      - name: Tests
        run: echo "Slow tests approved"

  run-slow-checks:
    name: Slow Checks
    needs:
      - approve-run-slow-tests
    uses: ./.github/workflows/slow-checks.yml
    (% if custom_workflows["slow-checks"].secrets %)
    secrets:
      (% for secret_name in custom_workflows["slow-checks"].secrets %)
      (( secret_name )): ${{ secrets.(( secret_name )) }}
      (% endfor %)
    (% endif %)
    permissions:
      contents: read

  (% if custom_workflows["merge-gate-extension"].exists %)
  merge-gate-extension:
    name: Extension
    uses: ./.github/workflows/merge-gate-extension.yml
    (% if custom_workflows["merge-gate-extension"].secrets %)
    secrets:
      (% for secret_name in custom_workflows["merge-gate-extension"].secrets %)
      (( secret_name )): ${{ secrets.(( secret_name )) }}
      (% endfor %)
    (% endif %)
    permissions:
      contents: read
  (% endif %)

  # This job ensures inputs have been executed successfully.
  allow-merge:
    name: Allow Merge
    if: ${{ !cancelled() }}
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    # If you need additional jobs to be part of the merge gate, add them below
    needs:
      - run-fast-checks
      - run-fast-tests
      - run-slow-checks
    (% if custom_workflows["merge-gate-extension"].exists %)
      - merge-gate-extension
    (% endif %)
    # To prevent accidentally merges, this step is required. For more details
    # see: https://github.com/exasol/python-toolbox/issues/563
    steps:
      - name: Branch Protection - failure if any ancestor failed or was cancelled
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        env:
          NEEDS_JSON: ${{ toJSON(needs) }}
        run: |
          echo "$NEEDS_JSON"
          exit 1
      - name: branch protection
        run: echo "All required checks passed. Merge allowed."
