name: PR-Merge

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:

  ci-job:
    name: Checks
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  publish-docs:
    name: Publish Documentation
    uses: ./.github/workflows/gh-pages.yml

  metrics:
    needs: [ ci-job ]
    uses: ./.github/workflows/report.yml
