(( workflow_header ))
name: Status Report

on:
  workflow_call:
    secrets:
      (( sonar_token_name )):
        required: true

jobs:

  report:
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    steps:
      - name: Check out Repository
        id: check-out-repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python & Poetry Environment
        id: set-up-python-and-poetry-environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v8
        with:
          python-version: "(( minimum_python_version ))"
          poetry-version: "(( dependency_manager_version ))"

      - name: Download Artifacts
        id: download-artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts

      - name: Copy Artifacts into Root Folder
        id: copy-artifacts-into-root-folder
        run: poetry run -- nox -s artifacts:copy -- artifacts

      - name: Validate Artifacts
        id: validate-artifacts
        run: poetry run -- nox -s artifacts:validate

      - name: Upload to Sonar
        id: upload-to-sonar
        env:
          SONAR_TOKEN: "${{ secrets.(( sonar_token_name )) }}"
        run: poetry run -- nox -s sonar:check

      - name: Generate GitHub Summary
        id: generate-github-summary
        run: |
          echo -e "# Summary\n" >> $GITHUB_STEP_SUMMARY
          poetry run -- nox -s dependency:licenses >> $GITHUB_STEP_SUMMARY
