name: Status Report

on:
  workflow_call:
    secrets:
      ALTERNATIVE_GITHUB_TOKEN:
        required: false

jobs:

  report:
    name: Generate Status Report
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ALTERNATIVE_GITHUB_TOKEN ||  secrets.GITHUB_TOKEN }}

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.5.0

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Copy Artifacts into Root Folder
        working-directory: ./artifacts
        run: |
          cp .coverage/.coverage ../
          cp .lint.txt/.lint.txt ../

      - name: Generate Report
        run: poetry run nox -s report -- -- --format json | tee metrics.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: metrics.json
          path: metrics.json

      - name: Generate GitHub Summary
        run: |
          echo -e "# Summary\n" >> $GITHUB_STEP_SUMMARY
          poetry run nox -s report -- -- --format markdown >> $GITHUB_STEP_SUMMARY
          echo -e "\n\n# Coverage\n" >> $GITHUB_STEP_SUMMARY
          poetry run coverage report -- --format markdown >> $GITHUB_STEP_SUMMARY
          echo  -e "\n\n# Static Code Analysis\n" >> $GITHUB_STEP_SUMMARY
          cat .lint.txt >> $GITHUB_STEP_SUMMARY
