name: Slow-Checks

on:
  workflow_call:

jobs:
  build-matrix:
    name: Generate Build Matrix
    uses: ./.github/workflows/matrix-all.yml
    permissions:
      contents: read

  tests:
    name: Integration-Tests (Python-${{ matrix.python-version }}, Exasol-${{ matrix.exasol-version}})
    needs: [ build-matrix ]
    runs-on: "(( os_version ))"
    permissions:
      contents: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v4
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: "(( dependency_manager_version ))"

      - name: Run Tests and Collect Coverage
        run: poetry run -- nox -s test:integration -- --coverage --db-version ${{ matrix.exasol-version }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: coverage-python${{ matrix.python-version }}-exasol${{ matrix.exasol-version }}-slow
          path: .coverage
          include-hidden-files: true
