rules:
  github-env:
    disable: true
  secrets-inherit:
    disable: true
  template-injection:
    disable: true
  unpinned-uses:
    config:
      policies:
        actions/checkout: hash-pin
        actions/cache: ref-pin
        actions/deploy-pages: ref-pin
        actions/download-artifact: ref-pin
        actions/setup-python: ref-pin
        actions/upload-artifact: ref-pin
        actions/upload-pages-artifact: hash-pin
        exasol/python-toolbox/.github/actions/python-environment: ref-pin
        ravsamhq/notify-slack-action: ref-pin
        zizmorcore/zizmor-action: hash-pin
  use-trusted-publishing:
    disable: true
