rules:
  github-env:
    disable: true
  secrets-inherit:
    disable: true
  template-injection:
    disable: true
  unpinned-uses:
    config:
      policies:
        "*": hash-pin
        exasol/python-toolbox/.github/actions/python-environment: ref-pin
  use-trusted-publishing:
    disable: true
