name: 'SIA'
description: 'The Security Issues Action creates github issues for open security issues in the repository'

# TODOs & Ideas
# * Change format to official CVE schema
# * Change action to support all kinds of formats
# * Add custom/additional details on ticket creation (e.g. dependency tree)
# * Output with json/markdown for reported/new security issues could be generated

inputs:

  command:
    description: 'Command for generating a security report'
    required: true

  format:
    description: 'Input format'
    required: false

  github-token:
    description: 'Github Token'
    required: True

runs:

  using: "composite"
  steps:

    - name: Setup Python (${{ inputs.python-version}})
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    # Pin this to specifically released version
    - name: Install Python Toolbox / Security tool
      shell: bash
      run: |
        pip install 'git+https://github.com/exasol/python-toolbox.git@feature/security-issues-action'

    - name: Create Security Issue Report
      shell: bash
      run: |
        ${{ inputs.command }} > input

    - name: Convert Report To Common Input Format
      shell: bash
      run: |
        tbx security cve convert ${{inputs.format}} < input > cves.jsonl

    # Remove irrelevant e.g. if issue already exists or existed
    # Info: a general ignore list could be added here to
    - name: Filter Issues
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: |
        tbx security cve filter github < cves.jsonl > issues.jsonl

    # Info: alternative issue tracker(s) could be added in the future
    - name: Create Issues
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: |
        tbx security cve create < issues.jsonl
