name: 'SIA'
description: 'The Security Issues Action creates github issues for open security issues in the repository'

# TODOs & Ideas
# * Change format to official CVE schema
# * Change action to support all kinds of formats
# * Add custom/additional details on ticket creation (e.g. dependency tree)
# * Output with json/markdown for reported/new security issues could be generated

inputs:

  command:
    description: 'Command which creates a security report for the repository'
    required: true
    default: "mvn org.sonatype.ossindex.maven:ossindex-maven-plugin:audit org.sonatype.ossindex.maven:ossindex-maven-plugin:audit-aggregate -Dossindex.reportFile=security-issues.json"

  format:
    description: 'Converter to apply on the scan-output before processing'
    required: false
    # passthrough in case of None
    default: maven

runs:

  using: "composite"
  steps:

    - name: Setup Python (${{ inputs.python-version}})
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    # Pin this to specifically released version
    - name: Install Python Toolbox / Security tool
      shell: bash
      run: |
        pip install 'git+https://github.com/exasol/python-toolbox.git@feature/security-issues-action'

    - name: Scan project for security issues
      shell: bash
      run: |
        ${{ inputs.command }} > scan-output

    - name: Convert output of command to common input format
      shell: bash
      run: |
        security-issues convert ${{inputs.format}} < scan-output > cves.json

    # Remove irrelevant e.g. if issue already exists or existed
    # Info: a general ignore list could be added here to
    - name: Filter issues
      shell: bash
      run: |
        security-issues filter github < cves.json > issues.json

    # Info: alternative issue tracker(s) could be added in the future
    - name: Create Issues
      shell: bash
      run: |
        security-issues create < issues.json
