name: 'SPPE'
description: 'Setup python and poetry environment'

inputs:

  python-version:
    description: 'Python version to use'
    required: true
    default: "3.8"

  poetry-version:
    description: 'Poetry version to use'
    required: true
    default: "1.2.2"

runs:

  using: "composite"
  steps:

    - name: Setup Poetry (${{ inputs.poetry-version }})
      run: pipx install poetry==${{ inputs.poetry-version }}
      shell: bash

    - name: Setup Python (${{ inputs.python-version}})
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'

    - name: Poetry install
      run: poetry install
      shell: bash
