name: 'SPPE'
description: 'Set up python and poetry environment'

inputs:

  python-version:
    description: 'Python version to use'
    required: true
    default: "3.10"

  poetry-version:
    description: 'Poetry version to use'
    required: true
    default: "2.1.4"

  working-directory:
    description: 'Working directory to use'
    required: false
    default: "."

  extras:
    description: 'Space-separated list of extras'
    required: false

  use-cache:
    description: 'Use cache for poetry environment'
    required: false
    default: 'true'

runs:

  using: "composite"
  steps:


    - name: Set up Python (${{ inputs.python-version}})
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Ensure curl
      shell: bash
      run: sudo apt update && sudo apt install -y curl

    - name: Set up Poetry (${{ inputs.poetry-version }})
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | POETRY_VERSION="${{ inputs.poetry-version }}" "$PYTHON_BINARY" -
        echo "PATH=$PATH:$HOME/.local/bin/" >> "$HOME/.bashrc"
      env:
        PYTHON_BINARY: "python${{ inputs.python-version }}"

    - name: Find Poetry environment path
      id: poetry-env-path
      shell: bash
      run: |
        POETRY_ENV_PATH=$(poetry config virtualenvs.path)
        echo "POETRY_ENV_PATH=$POETRY_ENV_PATH" >>  $GITHUB_OUTPUT

    - name: Cache Poetry environment
      if: ${{ inputs.use-cache == 'true' }}
      id: cache-poetry-env
      uses: actions/cache@v4
      with:
        path: ${{ steps.poetry-env-path.outputs.POETRY_ENV_PATH }}
        key: poetry-env-${{ runner.os }}-${{ runner.os }}-${{ inputs.poetry-version }}-${{ inputs.python-version }}-${{ inputs.extras }}

    - name: Poetry install with extras
      if: inputs.use-cache != 'true' || steps.cache-poetry-env.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        if [[ -n "$EXTRAS" ]]; then
          poetry install --extras "$EXTRAS"
        else
          poetry install
        fi

    - name: Validate Poetry environment
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        poetry run python --version
        poetry run python --version | grep "${{ inputs.python-version }}"
