name: 'SPPE'
description: 'Set up python and poetry environment'

inputs:

  python-version:
    description: 'Python version to use'
    required: true
    default: "3.10"

  poetry-version:
    description: 'Poetry version to use'
    required: true
    default: "2.2.1"

  working-directory:
    description: 'Working directory to use'
    required: false
    default: "."

  extras:
    description: 'Space-separated list of extras'
    required: false

  use-cache:
    description: 'Use cache for poetry environment'
    required: false
    default: 'true'

runs:

  using: "composite"
  steps:


    - name: Set up Python (${{ inputs.python-version}})
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Ensure wget
      shell: bash
      run: sudo apt update && sudo apt install -y wget

    - name: Set up Poetry (${{ inputs.poetry-version }})
      shell: bash
      run: |
        POETRY_VERSION="${{ inputs.poetry-version }}" "$PYTHON_BINARY" "${{ github.action_path }}/ext/get_poetry.py"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      env:
        PYTHON_BINARY: "python${{ inputs.python-version }}"

    - name: Setup cache variables
      id: setup-cache-variables
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "ImageOS=$ImageOS"
        echo "ImageVersion=$ImageVersion"
        POETRY_ENV_PATH=$(poetry config virtualenvs.path)
        POETRY_SHA=$(cat pyproject.toml poetry.lock | sha256sum | cut -f 1 -d " ") #Remove trailing dash
        # output to GITHUB_OUTPUT
        echo "IMAGE_OS=$ImageOS" >> $GITHUB_OUTPUT
        echo "IMAGE_VERSION=$ImageVersion" >> $GITHUB_OUTPUT
        echo "POETRY_ENV_PATH=$POETRY_ENV_PATH" >>  $GITHUB_OUTPUT
        echo "POETRY_SHA=$POETRY_SHA" >> $GITHUB_OUTPUT

    - name: Cache Poetry environment
      if: inputs.use-cache == 'true'
      id: cache-poetry-env
      uses: actions/cache@v4
      with:
        path: ${{ steps.setup-cache-variables.outputs.POETRY_ENV_PATH }}
        key: poetry-env-${{ steps.setup-cache-variables.outputs.POETRY_SHA }}-${{ steps.setup-cache-variables.outputs.IMAGE_OS }}-${{ steps.setup-cache-variables.outputs.IMAGE_VERSION }}-${{ runner.arch }}-${{ inputs.poetry-version }}-${{ inputs.python-version }}-${{ inputs.extras }}

    - name: Poetry install with extras
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        EXTRAS=$(echo "${{ inputs.extras }}" | tr -d ' ')
        if [[ -n "$EXTRAS" ]]; then
          poetry install --extras "$EXTRAS"
        else
          poetry install
        fi

    - name: Validate Poetry environment
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        poetry run python --version
        poetry run python --version | grep "${{ inputs.python-version }}"
