name: 'SPPE'
description: 'Setup python and poetry environment'

inputs:

  python-version:
    description: 'Python version to use'
    required: true
    default: "3.10"

  poetry-version:
    description: 'Poetry version to use'
    required: true
    default: "2.1.2"

  extras:
    description: 'Comma-separated list of extras'
    required: false

runs:

  using: "composite"
  steps:

    - name: Setup Python (${{ inputs.python-version}})
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'

    - name: Setup up pipx if not present
      shell: bash
      run: |
        if ! command -v pipx >/dev/null 2>&1; then
          python -m pip install --upgrade pip
          python -m pip install pipx
          pipx ensurepath
        fi

    - name: Setup Poetry (${{ inputs.poetry-version }})
      run: pipx install poetry==${{ inputs.poetry-version }}
      shell: bash

    - name: Poetry install with extras
      run: |
        EXTRAS=$(echo "${{ inputs.extras }}" | tr -d ' ')
        if [[ -n "$EXTRAS" ]]; then
          poetry install --with "$EXTRAS"
        else
          poetry install
        fi
      shell: bash
