name: 'SPPE'
description: 'Setup python and poetry environment'

inputs:

  python-version:
    description: 'Python version to use'
    required: true
    default: "3.10"

  poetry-version:
    description: 'Poetry version to use'
    required: true
    default: "2.1.2"

  working-directory:
    description: 'Working directory to use'
    required: true
    default: "."

runs:

  using: "composite"
  steps:

    - name: Setup Poetry (${{ inputs.poetry-version }})
      shell: bash
      run: pipx install poetry==${{ inputs.poetry-version }}

    - name: Setup Python (${{ inputs.python-version}})
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'

    - name: Poetry install
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: poetry install
