name: PR-Merge

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:

  ci-job:
    name: Checks
    uses: exasol/python-toolbox/.github/workflows/checks.yml@0.4.0

  publish-docs:
    name: Publish Documentation
    uses: exasol/python-toolbox/.github/workflows/gh-pages.yml@0.4.0

  metrics:
    needs: [ ci-job ]
    uses: exasol/python-toolbox/.github/workflows/report.yml@0.4.0
