name: Fast-Tests-Extension

on:
  workflow_call:

jobs:
  lint-imports:
    name: Lint Imports
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Check out Repository
        id: check-out-repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Python & Poetry Environment
        id: set-up-python-and-poetry-environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v8
        with:
          python-version: "3.10"
          poetry-version: "2.3.0"

      - name: Lint Imports
        id: lint-imports
        run: poetry run -- nox -s lint:import

  # This will be moved to a standard check in the checks.yml in:
  #  https://github.com/exasol/python-toolbox/issues/811
  lint-github-actions:
    name: Lint GitHub Actions
    runs-on: ubuntu-24.04
    steps:
      - name: Check out Repository
        id: check-out-repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Lint GitHub actions with Zizmor
        id: lint-github-actions
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
        with:
          advanced-security: false
