name: Fast-Tests-Extension

on:
  workflow_call:

jobs:
  lint-imports:
    name: Lint Imports
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Check out Repository
        id: check-out-repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up Python & Poetry Environment
        id: set-up-python-and-poetry-environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v10
        with:
          python-version: "3.10"
          poetry-version: "2.3.0"

      - name: Lint Imports
        id: lint-imports
        run: poetry run -- nox -s lint:import