name: Build Matrix (All Versions)

on:
  workflow_call:
    outputs:
      matrix:
        description: "Generates the all versions build matrix"
        value: ${{ jobs.set-matrix-all.outputs.matrix }}

jobs:
  set-matrix-all:
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    steps:
      - name: Check out Repository
        id: check-out-repository
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"

      - name: Set up Python & Poetry Environment
        id: set-up-python-and-poetry-environment
        uses: "exasol/python-toolbox/.github/actions/python-environment@de9c841d1e0c1d59b267900baf25da913330a25a"
        with:
          python-version: "3.10"
          poetry-version: "2.3.0"

      - name: Generate Matrix
        id: generate-matrix
        run: poetry run -- nox -s matrix:all

      - name: Set Matrix
        id: set-matrix
        run: |
          echo "matrix=$(poetry run -- nox -s matrix:all)" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
