name: Status Report

on:
  workflow_call:

jobs:

  Report:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/python-environment

      - name: Download Artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          path: ./artifacts

      - name: Copy Artifacts into Root Folder
        working-directory: ./artifacts
        run: |
          poetry run -- coverage combine --keep coverage-python*/.coverage
          # Errors during copying are ignored because they are checked in the next step
          cp .coverage ../ || true
          cp lint-python3.9/.lint.txt ../ || true
          cp lint-python3.9/.lint.json ../ || true
          cp security-python3.9/.security.json ../ || true

      - name: Validate Artifacts
        run: poetry run -- nox -s artifacts:validate

      - name: Generate Report
        run: poetry run -- nox -s project:report -- --format json | tee metrics.json

      - name: Prepare files for sonar
        run: |
          poetry run -- coverage xml -o ci-coverage.xml --include="exasol/toolbox/*"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=ci-coverage.xml
#            -Dsonar.python.pylint.reportPath .lint.json
#            -Dsonar.python.bandit.reportPaths .security.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: metrics.json
          path: metrics.json

      - name: Generate GitHub Summary
        run: |
          echo -e "# Summary\n" >> $GITHUB_STEP_SUMMARY
          poetry run -- nox -s project:report -- --format markdown >> $GITHUB_STEP_SUMMARY
          poetry run -- nox -s dependency:licenses >> $GITHUB_STEP_SUMMARY
          echo -e "\n\n# Coverage\n" >> $GITHUB_STEP_SUMMARY
          poetry run -- coverage report --format markdown >> $GITHUB_STEP_SUMMARY || true
          poetry run -- tbx lint pretty-print >> $GITHUB_STEP_SUMMARY
          poetry run -- tbx security pretty-print .security.json >> $GITHUB_STEP_SUMMARY
